### ISSUE TITLE
global pp

### ISSUE THREAD

**Issue by kevin-robb** [SoonerRobotics/igvc_software_2020#19]
I haven't tested this but you may need a "global pp" tag in the "timer_callback" function in "igvc_nav_node.py", since it is being referenced. Just noticed since I'm looking at this file to get an idea of how to write the NRC version.

**Comment by noahzemlin** [comment]
Not actually a problem. `global` is only needed when using assignment. This is because python 2 treats all assignments as local scoped, but assignment is never done in `igvc_nav_node.py` in a function.

**Comment by kevin-robb** [comment]
nice thank you for the info good pal
